version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - /root/minio/data:/data
      - /etc/letsencrypt/live/arpansahu.me:/root/.minio/certs
      # Uncomment these lines if using local paths on your machine
      # - /Users/arpansahu/projects/profile/minios3/data:/data
      # - /Users/arpansahu/projects/profile/certs:/root/.minio/certs
    environment: 
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # Uncomment and configure these lines if using custom certificates and URLs
      MINIO_CERT_PUBLIC_KEY: /root/.minio/certs/fullchain.pem
      MINIO_CERT_PRIVATE_KEY: /root/.minio/certs/privkey.pem
      # MINIO_SERVER_URL: ${MINIO_SERVER_URL}

    command: server /data --console-address ":9001" --address "0.0.0.0:9000"
    restart: unless-stopped