version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - /root/minio/data :/data
      - /root/certs:/root/.minio/certs
      # - /Users/arpansahu/projects/profile/minios3/data :/data
      # - /Users/arpansahu/projects/profile/certs:/root/.minio/certs
    environment: 
      MINIO_ROOT_USER: arpansahu
      MINIO_ROOT_PASSWORD: Kesar302minio
      # MINIO_CERT_PUBLIC_KEY: /etc/letsencrypt/live/arpansahu.me/fullchain.pem
      # MINIO_CERT_PRIVATE_KEY: /etc/letsencrypt/live/arpansahu.me/privatekey.pem
      # MINIO_SERVER_URL: https://minio.arpanshau.me:9002   
    command: server /data --console-address ":9001" --address "0.0.0.0:9000"
    restart: unless-stopped